= `pg_prefaulter`
include::front-matter.adoc[]
:keywords: postgresql, go, wal, fault, prefault, replication

[[usage]]
== Usage

[source,sh]
----
$ go get github.com/joyent/pg_prefaulter                // <1>
$ pg_prefaulter run                                     // <2>
$ pg_prefaulter -l DEBUG run                            // <3>
$ pg_prefaulter -l DEBUG run -D .pgdata_primary -p 5433 // <4>
$ pg_prefaulter -h                                      // <5>
$ pg_prefaulter run -h                                  // <6>
----
<1> Build and install `pg_prefaulter` into `$GOPATH/bin` (where `GOPATH` is
    likely `go env GOPATH`).
<2> The default mode of running `pg_prefaulter`
<3> Run `pg_preafulter` with ``DEBUG``-level logging.
<4> Run `pg_prefaulter` with various PG connect options.
<5> `pg_prefaulter` global help options
<6> ``pg_prefaulter``'s ``run``-specific options

NOTE: `pg_prefaulter` exposes itself as a https://github.com/google/gops[`gops`
client].

[[config]]
== Configuration Files

The following is an example configuration file.  This can be used instead of CLI
arguments.  The default configuration filename is `pg_prefaulter.toml`.  The
following is a reasonable default `pg_prefaulter.toml` configuration file.

[source,toml,numbered]
----
[log]
# level can be set to "DEBUG", "INFO", "WARN", "ERROR", or "FATAL"
#level = "INFO"

[postgresql]
#pgdata = "pgdata"
#database = "postgres"
#host = "/tmp"
#password = ""
#port = 5432
#user = "postgres"

[postgresql.xlog]
#pg_xlogdump-path = "/usr/local/bin/pg_xlogdump"

[circonus]
#enabled = true

[circonus.api]
# token is a required value if circonus.enabled=true
#token = ""

[circonus.broker]
# id should be set to "35" (the public HTTPTrap broker) if you have enterprise
# brokers configured in your account.
#id = 35

[circonus.check]
#tags = "dc1:mydc"
----

A complete configuration file with all options listed can be seen in
`pg_prefaulter.toml.sample-all`.

[[development]]
== Development

1. `make freshdb-primary`
2. `make freshdb-follower`
3. `make resetdb`
4. `make build`
5. `make check`
6. `./pg_prefaulter ...` # Iterate

To cross-compile and build a release use
https://github.com/goreleaser/goreleaser[`goreleaser`] and the `make release` or
`make release-snapshot` targets.  For development, the following should be
sufficient:

1. `go get -u github.com/goreleaser/goreleaser`
2. `goreleaser --snapshot --skip-validate --skip-publish --rm-dist`

[source,sh]
----
$ make
pg_prefaulter make(1) targets:
build            Build pg_prefaulter binary
check            Run go test
fmt              fmt and simplify the code
release-snapshot  Build a snapshot release
release          Build a release
vendor-status    Display the vendor/ status
vet              vet the binary (excluding dependencies)

cleandb-primary  Clean primary database
freshdb-primary  Drops and recreates the primary database
initdb-primary   initdb(1) a primary database
psql-primary     Open a psql(1) shell to the primary
startdb-primary  Start the primary database

cleandb-follower  Clean follower database
freshdb-follower  Drops and recreates the follower database
initdb-follower  initdb(1) a follower database
psql-follower    Open a psql(1) shell to the follower
startdb-follower  Start the follower database

createdb         Create the test database
dropdb           Reset the test database
gendata          Generate data in the primary
resetdb          Drop and recreate the database
testdb           Run database tests

controldata      Display pg_controldata(1) of the primary
psql             Open a psql(1) shell to the primary

clean            Clean target
cleandb-shard    Clean entire shard

help             This help message
----

[[todo]]
== TODO

* Add shell completion targets
* Add manpage generation targets
* Add markdown generation targets
* Add a generic status command to show:
** how far behind a given followers are when connected to the primary
** how far behind a given follower is when connected to the follower
* Add a SIGINFO handler to log stats about the current state of the process
* Expose expvar interface to enable online parameter twiddling
* Change the console logger to use mattn/isa-tty and use the console writer for
  pretty-printing.
* Fix the Circonus enable/disable (reported by Sam)
* Add a sampling logger to enable high-volume error points that provide
  sufficient fidelity of the underlying condition but doesn't drown the system
  in IO or useless repeated data.  Zerolog supports this but a global singleton
  sampling logger needs to be present someplace.
* Add a periodic background thread that visits each of the caches and prints
  various stats about the state of each of the caches.
* Move these TODO items over to GH issues
